### ISSUE TITLE
问下作者为什么用的GridLayoutManager来实现下拉刷新

### ISSUE THREAD

**Issue by SmallYuuu** [limxing/LFRecyclerView-Android#4]
为什么是网格布局不是线性布局？？

**Comment by limxing** [comment]
GridLayoutManager extends LinearLayoutManager，在 coding的时候某个地方需要强转，刚开始尝试过LinearLayoutManager，某些原因就是用了GridLayoutManager，具体原因忘记了，不过不影响我们使用。
